/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BntFooter: typeof import('./src/components/BntFooter.vue')['default']
    BntHeader: typeof import('./src/components/BntHeader.vue')['default']
    BntLocaleHeader: typeof import('./src/components/BntLocaleHeader.vue')['default']
    BubbleChart: typeof import('./src/components/BubbleChart.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    GuestMenu: typeof import('./src/components/GuestMenu.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InfoMessage: typeof import('./src/components/InfoMessage.vue')['default']
    LPHeader: typeof import('./src/components/LPHeader.vue')['default']
    NeedsDescription: typeof import('./src/components/NeedsDescription.vue')['default']
    RadarChart: typeof import('./src/components/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
